title: Sebestik's Status page
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.sebestik.tk
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: MultiBot
      category: ŠebesTech
      description: Multipurpose bot developed by ŠebesTech.
    - name: Website
      category: sebestik.tk
      description: GitHub Pages provided website (https://sebestik.tk)
    - name: Dashboard
      description: Apache2 server provided dashboard (hosted on RPi)
      category: sebestik.tk
    - name: Website
      description: GitHub Pages provided website (https://orgstechnic.tk)
      category: orgstechnic.tk
    - name: Dashboard
      category: orgstechnic.tk
      description: Apache2 server provided dashboard (hosted on RPi)
    - name: OrgsTechnic
      description: Common Bot developed by OrgsStudio.
      category: OrgsStudio
    - name: OrgsMusic
      category: OrgsStudio
      description: Music Bot developed by OrgsStudio.
    - name: Forum
      category: ŠebesTech
      description: Forum website (https://forum.sebestik.tk)
    - name: Redirect
      category: sebestik.tk
      description: Apache2 redirect (https://r.sebestik.tk)
    - name: Redirect
      category: orgstechnic.tk
      description: Apache2 redirect (https://r.orgstechnic.tk)
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: black
  logo: /img/sebestik.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: ŠebesTech
      description: ""
      closed: false
    - name: OrgsStudio
      untitled: false
      closed: false
    - name: sebestik.tk
    - name: orgstechnic.tk
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
